//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public decimal ProductId { get; set; }
        public string TypeOfActivity { get; set; }
        public decimal rate { get; set; }
        public decimal NoOfPeopleRequired { get; set; }
        public string LocationOfActivity { get; set; }
        public string IsBooked { get; set; }
        public string IsSaved { get; set; }
    }
}
