//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Air
    {
        public decimal ProductId { get; set; }
        public string name { get; set; }
        public decimal fare { get; set; }
        public decimal departureDate { get; set; }
        public decimal departureTime { get; set; }
        public decimal arrivalDate { get; set; }
        public decimal arrivalTime { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public string IsBooked { get; set; }
        public string IsSaved { get; set; }
    }
}
