//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public decimal ProductId { get; set; }
        public string name { get; set; }
        public decimal average { get; set; }
        public string RegisterationState { get; set; }
        public string fuelType { get; set; }
        public string gearType { get; set; }
        public decimal price { get; set; }
        public string IsBooked { get; set; }
        public string IsSaved { get; set; }
    }
}
