//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public decimal ProductId { get; set; }
        public string name { get; set; }
        public decimal noOfRooms { get; set; }
        public decimal rating { get; set; }
        public string HotelLocation { get; set; }
        public decimal RatePerRoom { get; set; }
        public string WifiAvailabilty { get; set; }
        public string IsBooked { get; set; }
        public string IsSaved { get; set; }
    }
}
